language: php

# run tests on php 5.4 as it's the main supported version, and we need min 5.4 for integrated web server
php:
  - 5.4

# list of paths to execute
env:
  - TEST_PATH="vendor/ezsystems/demobundle/EzSystems/DemoBundle/Features/"


# test only master (+ Pull requests)
branches:
  only:
    - master

# setup requirements for running tests
before_script:
  - mysql -e "CREATE DATABASE IF NOT EXISTS behattestdb;" -uroot
  - composer install --dev --prefer-dist --no-scripts
  - ./bin/behat_prepare_legacy.sh
  - composer run-script --dev post-install-cmd
  - php ezpublish/console --env=behat assetic:dump
  - ENVIRONMENT=behat
  - php ezpublish/console --no-interaction --env=behat ezpublish:test:init_db
  - php ezpublish/console --no-interaction --env=behat server:run -r ../bin/ezrouter.php localhost:9898 &
  - sleep 3

# execute phpunit as the script command
script: "bin/behat $TEST_PATH"

# disable mail notifications
notification:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
